# Copyright (C) 2023 - Damien Dejean <dam.dejean@gmail.com>

cc_library(
    name = "klibc",
    srcs = glob([
        "*.h",
        "*.c",
        "*.S",
    ]),
    hdrs = glob([
        "*.h",
        "include/*.h",
    ]),
    includes = ["include"],
    visibility = ["//visibility:public"],
)
