cc_library(
    name = "c",
    srcs = glob([
        "*.h",
        "*.c",
        "*.S",
    ]),
    hdrs = glob([
        "*.h",
        "include/*.h",
    ]),
    includes = ["include"],
    visibility = ["//visibility:public"],
)
