# Copyright (C) 2023 - Damien Dejean <dam.dejean@gmail.com>

cc_library(
    name = "utils",
    srcs = [
        "ringbuffer.c",
        "ringbuffer.h",
    ],
    hdrs = [
        "ringbuffer.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//lib:c"],
)
